# Generated by Django 4.0.5 on 2022-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.URLField(verbose_name='File')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ('id',),
            },
        ),
    ]
